name: ci

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  specs:
    name: ci
    runs-on: [actuated-16cpu-32gb, actuated-kvm]
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
            nix-build '<nixpkgs/nixos/tests/doas.nix>'
